### ISSUE TITLE
Live Progress Slider Bug

### ISSUE THREAD

**Issue by choco-lily** [nomomo/Chzzk_Scripts#1]
![image](https://github.com/user-attachments/assets/edc1616c-581c-4541-a3ef-809afc9ca9ae)
since today
can't see progress bar and can't click go to live

**Comment by nomomo** [comment]
Thank you for the report! I have updated the script to address the UI changes in today’s update. Please update to version 0.0.2 from the link : [https://github.com/nomomo/Chzzk_Scripts/raw/main/CHZZK_Live_Progress_Slider/CHZZK_Live_Progress_Slider.user.js](https://github.com/nomomo/Chzzk_Scripts/raw/main/CHZZK_Live_Progress_Slider/CHZZK_Live_Progress_Slider.user.js)
