### ISSUE TITLE
타임스탬프 관련 기능 추가 가능한가요??

### ISSUE THREAD

**Issue by jangforce08** [nomomo/Chzzk_Scripts#3]
트위치랑 다르게 치지직은 방송이 끝나있어도 채팅방이 클린? 상태가 아닌데다가
트위치때 너무 익숙해서 타임스탬프 기능이 필요한데... 가능한가요

**Comment by nomomo** [comment]
채팅창의 타임스탬프를 이야기 하시는건가요?
만약 그렇다면 치즈나이프 확장기능을 사용해보시기 바랍니다.

**Comment by jangforce08** [comment]
넵.. 사실 해당 확장프로그램 사용중이였는데 며칠전 치지직 업데이트 이후, 타임스탬프 기능을 사용하면 채팅창 오토스크롤이 안되는 버그?가 생겼습니다.
이 부분에 관련해서는 치즈나이프 만드신분께 디코와 홈페이지 메세지로 리포팅을 했는데 응답이 없어서 혹시 해당내용도 가능한가 여쭤봤습니다..
사실 치즈나이프 공홈 패치노트나 이런거에는 업데이트 된 내용이 없어서 깃허브에 보니 어제 픽스했다고 설명이 돼있네요.. 번거롭게 해드려 죄송합니다~
